version: "3.3"

services:
  crud_db:
    image: postgres:alpine
    container_name: crud_db
    ports:
      - 5432:5432
    volumes:
      - ./db:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud_db
      - POSTGRES_DATA=/data/postgres
  php:
    build: .
    container_name: crud_php
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
